batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 73
model_path: handwritten_to_digit/saved_model\202310141126
train_epochs: 1000
train_workers: 20
vocab: qGnhMB;by&t0c5.VeRgk WvaoidHS9Y6jK'xIO83T#E2w"Z4J!ULCD:psAlmu()FNrzQ7,1P-?f
width: 1408
