batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 73
model_path: handwritten_to_digit/saved_model\202310141141
train_epochs: 1000
train_workers: 20
vocab: '&jcTbgr2WG YJCR,i.fwh)zktMOy31PAZ:-K9#?uoel4I!BpnqQNDFvHSa(8m5''6Ex"0UVL7;sd'
width: 1408
