batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 73
model_path: handwritten_to_digit/saved_model\202310141124
train_epochs: 1000
train_workers: 20
vocab: -GlvY7xd6Pk&35CjhQm9Z)fEFJ.B(y0oS'igscrTL8AqN1DMI ,O2z!u#:4Wntab"U?R;HepwVK
width: 1408
