batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 73
model_path: handwritten_to_digit/saved_model\202310141143
train_epochs: 1000
train_workers: 20
vocab: kKlMqu1IrAOEn8Lx5.,oC:?tN3W2g"GQ96RwHYB;P#ivUD(0)&FV4m ybpJzS!jdfTZc7-e'ahs
width: 1408
