batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 73
model_path: handwritten_to_digit/saved_model\202310141133
train_epochs: 1000
train_workers: 20
vocab: :B0In mT9W(Zv8?R7rwJPf-SN4E16Hbyzleoh)QOd,a53F#D2ucG.ApsikjtUVq!K;x'YgL"MC&
width: 1408
